version: "3.8"
services:
  mondoc:
    image: ghcr.io/deep-jiwan/mondoc:latest
    container_name: my-mondoc
    network_mode: "host" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Docker socket for daemon access
    restart: unless-stopped


# Host netork allows for network related features to be used. 
# Currently only working with linux based docker deamon

#ghcr.io/deep-jiwan/mondoc:latest
#ghcr.io/deep-jiwan/mondoc:arm


